# Generated by Django 2.2.10 on 2021-08-14 21:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('company', models.CharField(max_length=200, null=True)),
                ('contractor', models.CharField(max_length=200, null=True)),
                ('postcode', models.CharField(max_length=8, null=True)),
                ('value', models.DecimalField(decimal_places=0, max_digits=7)),
                ('website', models.URLField(blank=True)),
                ('avatar', models.ImageField(blank=True, upload_to='uploads/img', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg'])])),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'Live'), (0, 'Completed')], default=1)),
                ('hourly_rate', models.IntegerField(default=35, validators=[django.core.validators.MinValueValidator(0)])),
                ('design_value_prelims', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99999999), django.core.validators.MinValueValidator(0)])),
                ('designer', models.ManyToManyField(related_name='pd', to=settings.AUTH_USER_MODEL)),
                ('pm', models.ManyToManyField(related_name='pm', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project',
                'ordering': ['-number'],
            },
        ),
    ]
