# Generated by Django 2.2.10 on 2021-08-14 21:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200, null=True)),
                ('is_fire', models.BooleanField(default=False)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('design_start', models.DateField(blank=True, default=datetime.datetime.today)),
                ('design_end', models.DateField(blank=True, default=datetime.datetime.today)),
                ('date_ga_first_issue_expected', models.DateField(blank=True, default=datetime.datetime.today)),
                ('date_ga_first_issue_actual', models.DateField(blank=True, default=datetime.datetime.today, null=True)),
                ('ga_first_issue_message', models.TextField(blank=True, max_length=500, null=True)),
                ('date_ga_first_status_expected', models.DateField(blank=True, default=datetime.datetime.today)),
                ('date_ga_first_status_actual', models.DateField(blank=True, default=datetime.datetime.today, null=True)),
                ('ga_first_status_message', models.TextField(blank=True, max_length=500, null=True)),
                ('date_ga_amendments_expected', models.DateField(blank=True, default=datetime.datetime.today)),
                ('date_ga_amendments_actual', models.DateField(blank=True, default=datetime.datetime.today, null=True)),
                ('ga_amendments_message', models.TextField(blank=True, max_length=500, null=True)),
                ('date_ga_final_approval_expected', models.DateField(blank=True, default=datetime.datetime.today)),
                ('date_ga_final_approval_actual', models.DateField(blank=True, default=datetime.datetime.today, null=True)),
                ('ga_final_approval_message', models.TextField(blank=True, max_length=500, null=True)),
                ('ts_first_issue_date_expected', models.DateField(blank=True, default=datetime.datetime.today)),
                ('ts_first_issue_date_actual', models.DateField(blank=True, default=datetime.datetime.today, null=True)),
                ('ts_first_issue_message', models.TextField(blank=True, max_length=500, null=True)),
                ('fabs_issue_date_expected', models.DateField(blank=True, default=datetime.datetime.today)),
                ('fabs_issue_date_actual', models.DateField(blank=True, default=datetime.datetime.today, null=True)),
                ('fabs_issue_message', models.TextField(blank=True, max_length=500, null=True)),
                ('ga_drawings', models.IntegerField(default=None, null=True)),
                ('ga_drawings_completed', models.IntegerField(default=None, null=True)),
                ('tech_subs', models.IntegerField(default=None, null=True)),
                ('tech_subs_completed', models.IntegerField(default=None, null=True)),
                ('fab_drawings', models.IntegerField(default=None, null=True)),
                ('fab_drawings_completed', models.IntegerField(default=None, null=True)),
                ('ab_drawings', models.IntegerField(default=None, null=True)),
                ('ab_drawings_completed', models.IntegerField(default=None, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
