# Generated by Django 2.2.10 on 2021-08-14 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_phase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='ab_drawings',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='ab_drawings_completed',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='fab_drawings',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='fab_drawings_completed',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='ga_drawings',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='ga_drawings_completed',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='tech_subs',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='tech_subs_completed',
        ),
    ]
