# Generated by Django 2.2.10 on 2021-08-14 22:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210814_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=datetime.datetime.today)),
                ('type', models.IntegerField(choices=[(0, 'GA Issue'), (1, 'GA Status'), (2, 'TS Issue'), (3, 'TS Status')], default=0)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Phase')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
