# Generated by Django 2.2.10 on 2021-08-14 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Eventset',
        ),
    ]
