# Generated by Django 2.2.10 on 2021-08-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20210814_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='date_ga_amendments_actual',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='date_ga_amendments_expected',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='date_ga_final_approval_actual',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='date_ga_final_approval_expected',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='date_ga_first_issue_actual',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='date_ga_first_issue_expected',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='date_ga_first_status_actual',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='date_ga_first_status_expected',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='fabs_issue_date_actual',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='fabs_issue_date_expected',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='fabs_issue_message',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='ga_amendments_message',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='ga_final_approval_message',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='ga_first_issue_message',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='ga_first_status_message',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='ts_first_issue_date_actual',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='ts_first_issue_date_expected',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='ts_first_issue_message',
        ),
        migrations.AddField(
            model_name='eventset',
            name='message',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
