# Generated by Django 2.2.10 on 2021-08-16 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20210814_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='company',
            new_name='branch',
        ),
    ]
