# Generated by Django 2.2.10 on 2021-09-01 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20210901_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='designer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='pd', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='pm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='pm', to=settings.AUTH_USER_MODEL),
        ),
    ]
