# Generated by Django 2.2.10 on 2021-09-01 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20210901_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='contractor',
        ),
        migrations.RemoveField(
            model_name='project',
            name='division',
        ),
    ]
