# Generated by Django 2.2.10 on 2021-09-01 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('projects', '0014_auto_20210901_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contractor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='contractor', to='companies.Company'),
        ),
        migrations.AddField(
            model_name='project',
            name='division',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='division', to='companies.Company'),
        ),
    ]
