# Generated by Django 2.2.10 on 2021-09-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('type', models.IntegerField(choices=[(1, 'Division'), (2, 'Contractor'), (3, 'Supplier')], default=1)),
                ('website', models.URLField(blank=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'company',
                'ordering': ['-id'],
            },
        ),
    ]
