# Generated by Django 2.2.10 on 2021-08-15 09:19

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0006_auto_20210814_2342'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=datetime.datetime.today)),
                ('time_spent', models.IntegerField(default=None, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(1)])),
                ('activity', models.IntegerField(choices=[(0, 'Survey'), (1, 'Intenal Design Meeting'), (2, 'External Design Meeting'), (3, 'Technical Submittals'), (4, 'GA Drawings'), (5, 'Fab Drawings'), (6, 'Revisions'), (7, 'As Builts')], default=4)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('phase', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projects.Phase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
