# Generated by Django 2.2.10 on 2021-08-15 08:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0006_auto_20210814_2342'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('type', models.IntegerField(choices=[(3, 'Technical Submittal'), (4, 'GAs and Detail'), (5, 'Fabrication Drawing'), (7, 'As Built')], default=4)),
                ('withdrawn', models.BooleanField(default=False)),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('phase', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='document_list', to='projects.Phase')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('active', models.BooleanField(default=True)),
                ('revision', models.CharField(default='P00', max_length=3)),
                ('document', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='workflow.Document')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('status', models.IntegerField(choices=[(0, 'A'), (1, 'B'), (2, 'C')], default=0)),
                ('active', models.BooleanField(default=True)),
                ('submission', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='workflow.Submission')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
